### PR TITLE
Bulk actions!

### PR DESCRIPTION
**Pull request by staugaard**
Support for bulk actions.

/cc @zendesk/octo

### CODE REVIEW

**Comment by steved** [comment]
+1

How are you going to handle the job status? I've been wanting to add a small utility class for it, but I've never really had to use it.

**Comment by staugaard** [comment]
Didn't realize that we already had a `ZendeskAPI::JobStatus` resource defined. Now I return instances of those.

**Comment by steved** [comment]
Huh, neither did I. I meant more along the lines of the actual polling for the job completion.

Still +1

**Comment by staugaard** [comment]
Did some small refactoring.

I might follow up with a PR for polling job statuses.

Still +1?

**Comment by steved** [comment]
yep

**Pull request merged**
