### PR TITLE
Use newest bundler in travis CI (Fix travis CI)

### PR DESCRIPTION
**Pull request by otoyo**
Use newest bundler reported in bundler/bundler#3559

Failure job
https://travis-ci.org/zendesk/zendesk_api_client_rb/jobs/273512217

### CODE REVIEW

**Comment by otoyo** [comment]
@grosser Would you merge this also, please?

**Comment by grosser** [comment]
looks good, but how about `before_install` and then don't override how `bundle install` works ?

**Comment by otoyo** [comment]
Indeed it might work.

**Comment by grosser** [comment]
thx!

**Pull request merged**
