### PR TITLE
added OrganizationSubscription resource

### PR DESCRIPTION
**Pull request by vgrigoruk**
/cc @grosser 

### Description

- Added support for https://developer.zendesk.com/rest_api/docs/core/organization_subscriptions resource
- Moved dev dependencies to Gemfile
- Fixed travis build for ruby 1.9.3

### Risks
* [low] Only new code may not work: `org.subscriptions` & `user.organization_subscriptions`

### CODE REVIEW

**Comment by grosser** [comment]
tests ? :)

**Comment by vgrigoruk** [comment]
@grosser, I've added live spec

**Comment by grosser** [comment]
❤️ 👍

**Comment by vgrigoruk** [comment]
I've merged my PR. 
What is the process to get a new version uploaded rubygems, @grosser ? Should I ask somebody to do it or should I request an access to our rubygems account (and do it myself)?

**Comment by grosser** [comment]
1.14.0 is out!
send me your rubygems email and I'll add you

**Pull request merged**
